language: go
go:
  - 1.2

before_script:
  - chmod +x *.sh
  - ./install-sdk.sh

install:
  - go get -u github.com/101loops/bdd
  - go get -u github.com/101loops/mcache
  - go get -u github.com/101loops/reflector
  - go get -u code.google.com/p/go.tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - go_appengine/goapp test -covermode=count -coverprofile=profile.cov .
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
