language: go
go:
  - 1.2

before_script:
  - chmod +x *.sh
  - ./install-sdk.sh
  - go get -u code.google.com/p/go.tools/cmd/cover
  - go get -u github.com/mattn/goveralls

install:
  - go get

script:
  - go_appengine/goapp test -v -covermode=count -coverprofile=profile.cov .
  - ~/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
